









//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CodeWF
{

    public static class MarkdownL
    {

        public static readonly string ImagePreviewTitle = "CodeWF.MarkdownL.ImagePreviewTitle";

        public static readonly string ImagePreviewZoomOut = "CodeWF.MarkdownL.ImagePreviewZoomOut";

        public static readonly string ImagePreviewZoomIn = "CodeWF.MarkdownL.ImagePreviewZoomIn";

        public static readonly string ImagePreviewRotateLeft = "CodeWF.MarkdownL.ImagePreviewRotateLeft";

        public static readonly string ImagePreviewRotateRight = "CodeWF.MarkdownL.ImagePreviewRotateRight";

        public static readonly string ImagePreviewSaveAs = "CodeWF.MarkdownL.ImagePreviewSaveAs";

        public static readonly string ImagePreviewImagesFileType = "CodeWF.MarkdownL.ImagePreviewImagesFileType";

        public static readonly string ImagePreviewZoomStatus = "CodeWF.MarkdownL.ImagePreviewZoomStatus";

        public static readonly string ImagePreviewActualSize = "CodeWF.MarkdownL.ImagePreviewActualSize";

        public static readonly string ImagePreviewFit = "CodeWF.MarkdownL.ImagePreviewFit";

        public static readonly string ImageLoadFailed = "CodeWF.MarkdownL.ImageLoadFailed";

        public static readonly string ImageFileNotFound = "CodeWF.MarkdownL.ImageFileNotFound";

        public static readonly string CopySelectedText = "CodeWF.MarkdownL.CopySelectedText";

        public static readonly string CopyRenderedText = "CodeWF.MarkdownL.CopyRenderedText";

        public static readonly string Copy = "CodeWF.MarkdownL.Copy";

    }


}

