//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeWF.Markdown.I18n {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeWF.Markdown.I18n.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        internal static string CodeWF_Markdown_Copy {
            get {
                return ResourceManager.GetString("CodeWF.Markdown.Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy rendered text 的本地化字符串。
        /// </summary>
        internal static string CodeWF_Markdown_CopyRenderedText {
            get {
                return ResourceManager.GetString("CodeWF.Markdown.CopyRenderedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy selected text 的本地化字符串。
        /// </summary>
        internal static string CodeWF_Markdown_CopySelectedText {
            get {
                return ResourceManager.GetString("CodeWF.Markdown.CopySelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File not found: {0} 的本地化字符串。
        /// </summary>
        internal static string CodeWF_Markdown_ImageFileNotFound {
            get {
                return ResourceManager.GetString("CodeWF.Markdown.ImageFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image failed to load: {0} 的本地化字符串。
        /// </summary>
        internal static string CodeWF_Markdown_ImageLoadFailed {
            get {
                return ResourceManager.GetString("CodeWF.Markdown.ImageLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1:1 的本地化字符串。
        /// </summary>
        internal static string CodeWF_Markdown_ImagePreviewActualSize {
            get {
                return ResourceManager.GetString("CodeWF.Markdown.ImagePreviewActualSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fit 的本地化字符串。
        /// </summary>
        internal static string CodeWF_Markdown_ImagePreviewFit {
            get {
                return ResourceManager.GetString("CodeWF.Markdown.ImagePreviewFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Images 的本地化字符串。
        /// </summary>
        internal static string CodeWF_Markdown_ImagePreviewImagesFileType {
            get {
                return ResourceManager.GetString("CodeWF.Markdown.ImagePreviewImagesFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rotate L 的本地化字符串。
        /// </summary>
        internal static string CodeWF_Markdown_ImagePreviewRotateLeft {
            get {
                return ResourceManager.GetString("CodeWF.Markdown.ImagePreviewRotateLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rotate R 的本地化字符串。
        /// </summary>
        internal static string CodeWF_Markdown_ImagePreviewRotateRight {
            get {
                return ResourceManager.GetString("CodeWF.Markdown.ImagePreviewRotateRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save As 的本地化字符串。
        /// </summary>
        internal static string CodeWF_Markdown_ImagePreviewSaveAs {
            get {
                return ResourceManager.GetString("CodeWF.Markdown.ImagePreviewSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Preview 的本地化字符串。
        /// </summary>
        internal static string CodeWF_Markdown_ImagePreviewTitle {
            get {
                return ResourceManager.GetString("CodeWF.Markdown.ImagePreviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom + 的本地化字符串。
        /// </summary>
        internal static string CodeWF_Markdown_ImagePreviewZoomIn {
            get {
                return ResourceManager.GetString("CodeWF.Markdown.ImagePreviewZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom - 的本地化字符串。
        /// </summary>
        internal static string CodeWF_Markdown_ImagePreviewZoomOut {
            get {
                return ResourceManager.GetString("CodeWF.Markdown.ImagePreviewZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0:P0} / {1} deg 的本地化字符串。
        /// </summary>
        internal static string CodeWF_Markdown_ImagePreviewZoomStatus {
            get {
                return ResourceManager.GetString("CodeWF.Markdown.ImagePreviewZoomStatus", resourceCulture);
            }
        }
    }
}
