//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Showcase.Main
{
    public static class MainWindow
    {
        public static readonly string Title = "Showcase.Main.MainWindow.Title";
        public static readonly string AppName = "Showcase.Main.MainWindow.AppName";
        public static readonly string ControlListTitle = "Showcase.Main.MainWindow.ControlListTitle";
        public static readonly string SearchWatermark = "Showcase.Main.MainWindow.SearchWatermark";
        public static readonly string LanguageLabel = "Showcase.Main.MainWindow.LanguageLabel";
        public static readonly string ThemeLabel = "Showcase.Main.MainWindow.ThemeLabel";
        public static readonly string ThemeLight = "Showcase.Main.MainWindow.ThemeLight";
        public static readonly string ThemeDark = "Showcase.Main.MainWindow.ThemeDark";
        public static readonly string NoMatches = "Showcase.Main.MainWindow.NoMatches";
        public static readonly string TabOverview = "Showcase.Main.MainWindow.TabOverview";
        public static readonly string TabTransfer = "Showcase.Main.MainWindow.TabTransfer";
        public static readonly string TabVComboBox = "Showcase.Main.MainWindow.TabVComboBox";
        public static readonly string TabTabControl = "Showcase.Main.MainWindow.TabTabControl";
        public static readonly string TabStatusBadge = "Showcase.Main.MainWindow.TabStatusBadge";
        public static readonly string TabStatusCard = "Showcase.Main.MainWindow.TabStatusCard";
        public static readonly string TabMarkup = "Showcase.Main.MainWindow.TabMarkup";
        public static readonly string TabAnimatedImage = "Showcase.Main.MainWindow.TabAnimatedImage";
        public static readonly string TabWindowDemos = "Showcase.Main.MainWindow.TabWindowDemos";
    }


}


namespace Showcase.Pages
{
    public static class OverviewDemo
    {
        public static readonly string Title = "Showcase.Pages.OverviewDemo.Title";
        public static readonly string Description = "Showcase.Pages.OverviewDemo.Description";
        public static readonly string ControlSamples = "Showcase.Pages.OverviewDemo.ControlSamples";
        public static readonly string ControlSamplesDesc = "Showcase.Pages.OverviewDemo.ControlSamplesDesc";
        public static readonly string MarkupExtensions = "Showcase.Pages.OverviewDemo.MarkupExtensions";
        public static readonly string MarkupExtensionsDesc = "Showcase.Pages.OverviewDemo.MarkupExtensionsDesc";
        public static readonly string WindowSamples = "Showcase.Pages.OverviewDemo.WindowSamples";
        public static readonly string WindowSamplesDesc = "Showcase.Pages.OverviewDemo.WindowSamplesDesc";
        public static readonly string ThemeI18n = "Showcase.Pages.OverviewDemo.ThemeI18n";
        public static readonly string ThemeI18nDesc = "Showcase.Pages.OverviewDemo.ThemeI18nDesc";
    }


    public static class TransferDemo
    {
        public static readonly string Title = "Showcase.Pages.TransferDemo.Title";
        public static readonly string Description = "Showcase.Pages.TransferDemo.Description";
        public static readonly string LeftHeader = "Showcase.Pages.TransferDemo.LeftHeader";
        public static readonly string RightHeader = "Showcase.Pages.TransferDemo.RightHeader";
        public static readonly string LeftTitleLabel = "Showcase.Pages.TransferDemo.LeftTitleLabel";
        public static readonly string RightTitleLabel = "Showcase.Pages.TransferDemo.RightTitleLabel";
        public static readonly string SelectedLabel = "Showcase.Pages.TransferDemo.SelectedLabel";
        public static readonly string EmptySelection = "Showcase.Pages.TransferDemo.EmptySelection";
        public static readonly string Item01 = "Showcase.Pages.TransferDemo.Item01";
        public static readonly string Item02 = "Showcase.Pages.TransferDemo.Item02";
        public static readonly string Item03 = "Showcase.Pages.TransferDemo.Item03";
        public static readonly string Item04 = "Showcase.Pages.TransferDemo.Item04";
        public static readonly string Item05 = "Showcase.Pages.TransferDemo.Item05";
        public static readonly string Item06 = "Showcase.Pages.TransferDemo.Item06";
        public static readonly string Item07 = "Showcase.Pages.TransferDemo.Item07";
        public static readonly string Item08 = "Showcase.Pages.TransferDemo.Item08";
        public static readonly string Item09 = "Showcase.Pages.TransferDemo.Item09";
        public static readonly string Item10 = "Showcase.Pages.TransferDemo.Item10";
        public static readonly string Item11 = "Showcase.Pages.TransferDemo.Item11";
        public static readonly string Item12 = "Showcase.Pages.TransferDemo.Item12";
        public static readonly string Item13 = "Showcase.Pages.TransferDemo.Item13";
        public static readonly string Item14 = "Showcase.Pages.TransferDemo.Item14";
        public static readonly string Item15 = "Showcase.Pages.TransferDemo.Item15";
    }


    public static class VComboBoxDemo
    {
        public static readonly string Title = "Showcase.Pages.VComboBoxDemo.Title";
        public static readonly string Description = "Showcase.Pages.VComboBoxDemo.Description";
        public static readonly string New = "Showcase.Pages.VComboBoxDemo.New";
        public static readonly string Configure = "Showcase.Pages.VComboBoxDemo.Configure";
        public static readonly string Edit = "Showcase.Pages.VComboBoxDemo.Edit";
        public static readonly string Refresh = "Showcase.Pages.VComboBoxDemo.Refresh";
        public static readonly string PopupHeader = "Showcase.Pages.VComboBoxDemo.PopupHeader";
        public static readonly string PopupWatermark = "Showcase.Pages.VComboBoxDemo.PopupWatermark";
        public static readonly string ScenarioTitle = "Showcase.Pages.VComboBoxDemo.ScenarioTitle";
        public static readonly string Scenario1 = "Showcase.Pages.VComboBoxDemo.Scenario1";
        public static readonly string Scenario2 = "Showcase.Pages.VComboBoxDemo.Scenario2";
        public static readonly string Scenario3 = "Showcase.Pages.VComboBoxDemo.Scenario3";
        public static readonly string WarningAll = "Showcase.Pages.VComboBoxDemo.WarningAll";
        public static readonly string WarningAlert = "Showcase.Pages.VComboBoxDemo.WarningAlert";
        public static readonly string WarningNormal = "Showcase.Pages.VComboBoxDemo.WarningNormal";
        public static readonly string SelectionBoxWarning = "Showcase.Pages.VComboBoxDemo.SelectionBoxWarning";
        public static readonly string ToolbarTitle = "Showcase.Pages.VComboBoxDemo.ToolbarTitle";
        public static readonly string ToolbarDescription = "Showcase.Pages.VComboBoxDemo.ToolbarDescription";
        public static readonly string LivePreview = "Showcase.Pages.VComboBoxDemo.LivePreview";
        public static readonly string VerticalSelectorTitle = "Showcase.Pages.VComboBoxDemo.VerticalSelectorTitle";
        public static readonly string VerticalSelectorDescription = "Showcase.Pages.VComboBoxDemo.VerticalSelectorDescription";
        public static readonly string FilterResultTitle = "Showcase.Pages.VComboBoxDemo.FilterResultTitle";
        public static readonly string FilterDelayed = "Showcase.Pages.VComboBoxDemo.FilterDelayed";
        public static readonly string FilterPendingConfig = "Showcase.Pages.VComboBoxDemo.FilterPendingConfig";
        public static readonly string FilterNormal = "Showcase.Pages.VComboBoxDemo.FilterNormal";
        public static readonly string CurrentPolicyTitle = "Showcase.Pages.VComboBoxDemo.CurrentPolicyTitle";
        public static readonly string CurrentPolicyDescription = "Showcase.Pages.VComboBoxDemo.CurrentPolicyDescription";
    }


    public static class TabControlDemo
    {
        public static readonly string Title = "Showcase.Pages.TabControlDemo.Title";
        public static readonly string Description = "Showcase.Pages.TabControlDemo.Description";
        public static readonly string BusinessStyle = "Showcase.Pages.TabControlDemo.BusinessStyle";
        public static readonly string BrandStyle = "Showcase.Pages.TabControlDemo.BrandStyle";
        public static readonly string DataManagement = "Showcase.Pages.TabControlDemo.DataManagement";
        public static readonly string SystemSettings = "Showcase.Pages.TabControlDemo.SystemSettings";
        public static readonly string UserCenter = "Showcase.Pages.TabControlDemo.UserCenter";
        public static readonly string LogRecords = "Showcase.Pages.TabControlDemo.LogRecords";
        public static readonly string HelpDocs = "Showcase.Pages.TabControlDemo.HelpDocs";
        public static readonly string BusinessContentDesc = "Showcase.Pages.TabControlDemo.BusinessContentDesc";
        public static readonly string ContentDemo = "Showcase.Pages.TabControlDemo.ContentDemo";
        public static readonly string DataQuality = "Showcase.Pages.TabControlDemo.DataQuality";
        public static readonly string Last24hPassRate = "Showcase.Pages.TabControlDemo.Last24hPassRate";
        public static readonly string Pending = "Showcase.Pages.TabControlDemo.Pending";
        public static readonly string ManualReviewRecords = "Showcase.Pages.TabControlDemo.ManualReviewRecords";
        public static readonly string SyncStatus = "Showcase.Pages.TabControlDemo.SyncStatus";
        public static readonly string Normal = "Showcase.Pages.TabControlDemo.Normal";
        public static readonly string LastSync2Min = "Showcase.Pages.TabControlDemo.LastSync2Min";
        public static readonly string SettingsContentDesc = "Showcase.Pages.TabControlDemo.SettingsContentDesc";
        public static readonly string UserCenterContentDesc = "Showcase.Pages.TabControlDemo.UserCenterContentDesc";
        public static readonly string LogRecordsContentDesc = "Showcase.Pages.TabControlDemo.LogRecordsContentDesc";
        public static readonly string HelpDocsContentDesc = "Showcase.Pages.TabControlDemo.HelpDocsContentDesc";
        public static readonly string BrandContentDesc = "Showcase.Pages.TabControlDemo.BrandContentDesc";
        public static readonly string BrandContentTitle = "Showcase.Pages.TabControlDemo.BrandContentTitle";
        public static readonly string BrandContentBody = "Showcase.Pages.TabControlDemo.BrandContentBody";
        public static readonly string ViewDetails = "Showcase.Pages.TabControlDemo.ViewDetails";
    }


    public static class StatusBadgeDemo
    {
        public static readonly string Title = "Showcase.Pages.StatusBadgeDemo.Title";
        public static readonly string SemanticStatus = "Showcase.Pages.StatusBadgeDemo.SemanticStatus";
        public static readonly string SemanticDesc = "Showcase.Pages.StatusBadgeDemo.SemanticDesc";
        public static readonly string SizeChanges = "Showcase.Pages.StatusBadgeDemo.SizeChanges";
        public static readonly string SizeDesc = "Showcase.Pages.StatusBadgeDemo.SizeDesc";
        public static readonly string ContentLength = "Showcase.Pages.StatusBadgeDemo.ContentLength";
        public static readonly string ContentDesc = "Showcase.Pages.StatusBadgeDemo.ContentDesc";
        public static readonly string Appearance = "Showcase.Pages.StatusBadgeDemo.Appearance";
        public static readonly string AppearanceDesc = "Showcase.Pages.StatusBadgeDemo.AppearanceDesc";
        public static readonly string CornerRadius = "Showcase.Pages.StatusBadgeDemo.CornerRadius";
        public static readonly string PaddingDensity = "Showcase.Pages.StatusBadgeDemo.PaddingDensity";
        public static readonly string Scenarios = "Showcase.Pages.StatusBadgeDemo.Scenarios";
        public static readonly string ScenariosDesc = "Showcase.Pages.StatusBadgeDemo.ScenariosDesc";
        public static readonly string Metrics = "Showcase.Pages.StatusBadgeDemo.Metrics";
        public static readonly string SystemStatus = "Showcase.Pages.StatusBadgeDemo.SystemStatus";
        public static readonly string TaskTracking = "Showcase.Pages.StatusBadgeDemo.TaskTracking";
        public static readonly string Debug = "Showcase.Pages.StatusBadgeDemo.Debug";
        public static readonly string Running = "Showcase.Pages.StatusBadgeDemo.Running";
        public static readonly string Info = "Showcase.Pages.StatusBadgeDemo.Info";
        public static readonly string Completed = "Showcase.Pages.StatusBadgeDemo.Completed";
        public static readonly string Warn = "Showcase.Pages.StatusBadgeDemo.Warn";
        public static readonly string Review = "Showcase.Pages.StatusBadgeDemo.Review";
        public static readonly string Error = "Showcase.Pages.StatusBadgeDemo.Error";
        public static readonly string Fix = "Showcase.Pages.StatusBadgeDemo.Fix";
        public static readonly string Fatal = "Showcase.Pages.StatusBadgeDemo.Fatal";
        public static readonly string Critical = "Showcase.Pages.StatusBadgeDemo.Critical";
        public static readonly string Emphasis = "Showcase.Pages.StatusBadgeDemo.Emphasis";
        public static readonly string ShortText = "Showcase.Pages.StatusBadgeDemo.ShortText";
        public static readonly string MediumLabel = "Showcase.Pages.StatusBadgeDemo.MediumLabel";
        public static readonly string LongCategory = "Showcase.Pages.StatusBadgeDemo.LongCategory";
        public static readonly string LongStatus = "Showcase.Pages.StatusBadgeDemo.LongStatus";
        public static readonly string Sharp = "Showcase.Pages.StatusBadgeDemo.Sharp";
        public static readonly string Soft = "Showcase.Pages.StatusBadgeDemo.Soft";
        public static readonly string SmallRadius = "Showcase.Pages.StatusBadgeDemo.SmallRadius";
        public static readonly string MediumRadius = "Showcase.Pages.StatusBadgeDemo.MediumRadius";
        public static readonly string Rounded = "Showcase.Pages.StatusBadgeDemo.Rounded";
        public static readonly string Pill = "Showcase.Pages.StatusBadgeDemo.Pill";
        public static readonly string Compact = "Showcase.Pages.StatusBadgeDemo.Compact";
        public static readonly string Dense = "Showcase.Pages.StatusBadgeDemo.Dense";
        public static readonly string Balanced = "Showcase.Pages.StatusBadgeDemo.Balanced";
        public static readonly string Roomy = "Showcase.Pages.StatusBadgeDemo.Roomy";
        public static readonly string Relaxed = "Showcase.Pages.StatusBadgeDemo.Relaxed";
        public static readonly string Downloads = "Showcase.Pages.StatusBadgeDemo.Downloads";
        public static readonly string ActiveUsers = "Showcase.Pages.StatusBadgeDemo.ActiveUsers";
        public static readonly string Conversion = "Showcase.Pages.StatusBadgeDemo.Conversion";
        public static readonly string Satisfaction = "Showcase.Pages.StatusBadgeDemo.Satisfaction";
        public static readonly string System = "Showcase.Pages.StatusBadgeDemo.System";
        public static readonly string Storage = "Showcase.Pages.StatusBadgeDemo.Storage";
        public static readonly string StorageLow = "Showcase.Pages.StatusBadgeDemo.StorageLow";
        public static readonly string Sync = "Showcase.Pages.StatusBadgeDemo.Sync";
        public static readonly string Failed = "Showcase.Pages.StatusBadgeDemo.Failed";
        public static readonly string Database = "Showcase.Pages.StatusBadgeDemo.Database";
        public static readonly string Disconnected = "Showcase.Pages.StatusBadgeDemo.Disconnected";
        public static readonly string InProgress = "Showcase.Pages.StatusBadgeDemo.InProgress";
        public static readonly string Overdue = "Showcase.Pages.StatusBadgeDemo.Overdue";
    }


    public static class StatusCardDemo
    {
        public static readonly string Title = "Showcase.Pages.StatusCardDemo.Title";
        public static readonly string Description = "Showcase.Pages.StatusCardDemo.Description";
        public static readonly string Gateway = "Showcase.Pages.StatusCardDemo.Gateway";
        public static readonly string Collector = "Showcase.Pages.StatusCardDemo.Collector";
        public static readonly string Storage = "Showcase.Pages.StatusCardDemo.Storage";
        public static readonly string ComputeNode = "Showcase.Pages.StatusCardDemo.ComputeNode";
        public static readonly string Database = "Showcase.Pages.StatusCardDemo.Database";
        public static readonly string Debug = "Showcase.Pages.StatusCardDemo.Debug";
        public static readonly string Info = "Showcase.Pages.StatusCardDemo.Info";
        public static readonly string Warn = "Showcase.Pages.StatusCardDemo.Warn";
        public static readonly string Error = "Showcase.Pages.StatusCardDemo.Error";
        public static readonly string Fatal = "Showcase.Pages.StatusCardDemo.Fatal";
        public static readonly string RecommendedUsage = "Showcase.Pages.StatusCardDemo.RecommendedUsage";
        public static readonly string Usage1 = "Showcase.Pages.StatusCardDemo.Usage1";
        public static readonly string Usage2 = "Showcase.Pages.StatusCardDemo.Usage2";
        public static readonly string Usage3 = "Showcase.Pages.StatusCardDemo.Usage3";
        public static readonly string HealthOverviewTitle = "Showcase.Pages.StatusCardDemo.HealthOverviewTitle";
        public static readonly string HealthOverviewDesc = "Showcase.Pages.StatusCardDemo.HealthOverviewDesc";
        public static readonly string StatusVariantsTag = "Showcase.Pages.StatusCardDemo.StatusVariantsTag";
        public static readonly string CompactView = "Showcase.Pages.StatusCardDemo.CompactView";
        public static readonly string CompactViewDesc = "Showcase.Pages.StatusCardDemo.CompactViewDesc";
        public static readonly string AlertView = "Showcase.Pages.StatusCardDemo.AlertView";
        public static readonly string AlertViewDesc = "Showcase.Pages.StatusCardDemo.AlertViewDesc";
        public static readonly string ThemeResources = "Showcase.Pages.StatusCardDemo.ThemeResources";
    }


    public static class MarkupExtensionsDemo
    {
        public static readonly string Title = "Showcase.Pages.MarkupExtensionsDemo.Title";
        public static readonly string Description = "Showcase.Pages.MarkupExtensionsDemo.Description";
        public static readonly string PipelineConsole = "Showcase.Pages.MarkupExtensionsDemo.PipelineConsole";
        public static readonly string PipelineRunning = "Showcase.Pages.MarkupExtensionsDemo.PipelineRunning";
        public static readonly string PipelinePaused = "Showcase.Pages.MarkupExtensionsDemo.PipelinePaused";
        public static readonly string PausePipeline = "Showcase.Pages.MarkupExtensionsDemo.PausePipeline";
        public static readonly string StartPipeline = "Showcase.Pages.MarkupExtensionsDemo.StartPipeline";
        public static readonly string AutoPublishEnabled = "Showcase.Pages.MarkupExtensionsDemo.AutoPublishEnabled";
        public static readonly string AutoPublishEnabledDesc = "Showcase.Pages.MarkupExtensionsDemo.AutoPublishEnabledDesc";
        public static readonly string AutoPublishPaused = "Showcase.Pages.MarkupExtensionsDemo.AutoPublishPaused";
        public static readonly string AutoPublishPausedDesc = "Showcase.Pages.MarkupExtensionsDemo.AutoPublishPausedDesc";
        public static readonly string UnknownStatus = "Showcase.Pages.MarkupExtensionsDemo.UnknownStatus";
        public static readonly string UnknownStatusDesc = "Showcase.Pages.MarkupExtensionsDemo.UnknownStatusDesc";
        public static readonly string NextStatus = "Showcase.Pages.MarkupExtensionsDemo.NextStatus";
        public static readonly string QueueTitle = "Showcase.Pages.MarkupExtensionsDemo.QueueTitle";
        public static readonly string QueueEmpty = "Showcase.Pages.MarkupExtensionsDemo.QueueEmpty";
        public static readonly string QueueNotEmpty = "Showcase.Pages.MarkupExtensionsDemo.QueueNotEmpty";
        public static readonly string Clear = "Showcase.Pages.MarkupExtensionsDemo.Clear";
        public static readonly string Reset = "Showcase.Pages.MarkupExtensionsDemo.Reset";
        public static readonly string SwitchSourceTitle = "Showcase.Pages.MarkupExtensionsDemo.SwitchSourceTitle";
        public static readonly string SwitchSourceDesc = "Showcase.Pages.MarkupExtensionsDemo.SwitchSourceDesc";
        public static readonly string Healthy = "Showcase.Pages.MarkupExtensionsDemo.Healthy";
        public static readonly string Delayed = "Showcase.Pages.MarkupExtensionsDemo.Delayed";
        public static readonly string Failed = "Showcase.Pages.MarkupExtensionsDemo.Failed";
        public static readonly string Locked = "Showcase.Pages.MarkupExtensionsDemo.Locked";
        public static readonly string CurrentXamlTitle = "Showcase.Pages.MarkupExtensionsDemo.CurrentXamlTitle";
        public static readonly string IfSyntaxTitle = "Showcase.Pages.MarkupExtensionsDemo.IfSyntaxTitle";
        public static readonly string HealthHealthyTitle = "Showcase.Pages.MarkupExtensionsDemo.HealthHealthyTitle";
        public static readonly string HealthHealthyDesc = "Showcase.Pages.MarkupExtensionsDemo.HealthHealthyDesc";
        public static readonly string HealthDelayedTitle = "Showcase.Pages.MarkupExtensionsDemo.HealthDelayedTitle";
        public static readonly string HealthDelayedDesc = "Showcase.Pages.MarkupExtensionsDemo.HealthDelayedDesc";
        public static readonly string HealthFailedTitle = "Showcase.Pages.MarkupExtensionsDemo.HealthFailedTitle";
        public static readonly string HealthFailedDesc = "Showcase.Pages.MarkupExtensionsDemo.HealthFailedDesc";
        public static readonly string HealthLockedTitle = "Showcase.Pages.MarkupExtensionsDemo.HealthLockedTitle";
        public static readonly string HealthLockedDesc = "Showcase.Pages.MarkupExtensionsDemo.HealthLockedDesc";
        public static readonly string QueueItemApi = "Showcase.Pages.MarkupExtensionsDemo.QueueItemApi";
        public static readonly string QueueItemDesktop = "Showcase.Pages.MarkupExtensionsDemo.QueueItemDesktop";
        public static readonly string QueueItemDocs = "Showcase.Pages.MarkupExtensionsDemo.QueueItemDocs";
        public static readonly string QueueItemSync = "Showcase.Pages.MarkupExtensionsDemo.QueueItemSync";
    }


    public static class AnimatedImageDemo
    {
        public static readonly string Title = "Showcase.Pages.AnimatedImageDemo.Title";
        public static readonly string Description = "Showcase.Pages.AnimatedImageDemo.Description";
        public static readonly string LocalResource = "Showcase.Pages.AnimatedImageDemo.LocalResource";
        public static readonly string NetworkResource = "Showcase.Pages.AnimatedImageDemo.NetworkResource";
        public static readonly string LoadingNetworkGif = "Showcase.Pages.AnimatedImageDemo.LoadingNetworkGif";
        public static readonly string NetworkFallback = "Showcase.Pages.AnimatedImageDemo.NetworkFallback";
    }


    public static class WindowDemo
    {
        public static readonly string Title = "Showcase.Pages.WindowDemo.Title";
        public static readonly string Description = "Showcase.Pages.WindowDemo.Description";
        public static readonly string ShellTag = "Showcase.Pages.WindowDemo.ShellTag";
        public static readonly string NativeGroup = "Showcase.Pages.WindowDemo.NativeGroup";
        public static readonly string NativeDesc = "Showcase.Pages.WindowDemo.NativeDesc";
        public static readonly string OpenNative = "Showcase.Pages.WindowDemo.OpenNative";
        public static readonly string NativeNone = "Showcase.Pages.WindowDemo.NativeNone";
        public static readonly string NativeMove = "Showcase.Pages.WindowDemo.NativeMove";
        public static readonly string NativeDark = "Showcase.Pages.WindowDemo.NativeDark";
        public static readonly string NativeTall = "Showcase.Pages.WindowDemo.NativeTall";
        public static readonly string NativeShape = "Showcase.Pages.WindowDemo.NativeShape";
        public static readonly string NativeStar = "Showcase.Pages.WindowDemo.NativeStar";
        public static readonly string NativeBlob = "Showcase.Pages.WindowDemo.NativeBlob";
        public static readonly string UrsaGroup = "Showcase.Pages.WindowDemo.UrsaGroup";
        public static readonly string UrsaDesc = "Showcase.Pages.WindowDemo.UrsaDesc";
        public static readonly string StandardUrsa = "Showcase.Pages.WindowDemo.StandardUrsa";
        public static readonly string BorderlessUrsa = "Showcase.Pages.WindowDemo.BorderlessUrsa";
        public static readonly string BorderlessDraggableUrsa = "Showcase.Pages.WindowDemo.BorderlessDraggableUrsa";
        public static readonly string UrsaDark = "Showcase.Pages.WindowDemo.UrsaDark";
        public static readonly string UrsaAccent = "Showcase.Pages.WindowDemo.UrsaAccent";
        public static readonly string UrsaCompact = "Showcase.Pages.WindowDemo.UrsaCompact";
        public static readonly string UrsaTall = "Showcase.Pages.WindowDemo.UrsaTall";
        public static readonly string UrsaShape = "Showcase.Pages.WindowDemo.UrsaShape";
        public static readonly string UrsaStar = "Showcase.Pages.WindowDemo.UrsaStar";
        public static readonly string UrsaBlob = "Showcase.Pages.WindowDemo.UrsaBlob";
        public static readonly string CodeWFGroup = "Showcase.Pages.WindowDemo.CodeWFGroup";
        public static readonly string CodeWFDesc = "Showcase.Pages.WindowDemo.CodeWFDesc";
        public static readonly string StandardCodeWF = "Showcase.Pages.WindowDemo.StandardCodeWF";
        public static readonly string CodeWFDark = "Showcase.Pages.WindowDemo.CodeWFDark";
        public static readonly string CodeWFAccent = "Showcase.Pages.WindowDemo.CodeWFAccent";
        public static readonly string CodeWFCompact = "Showcase.Pages.WindowDemo.CodeWFCompact";
        public static readonly string CodeWFTall = "Showcase.Pages.WindowDemo.CodeWFTall";
        public static readonly string CodeWFServiceConsole = "Showcase.Pages.WindowDemo.CodeWFServiceConsole";
        public static readonly string CodeWFShape = "Showcase.Pages.WindowDemo.CodeWFShape";
        public static readonly string CodeWFStar = "Showcase.Pages.WindowDemo.CodeWFStar";
        public static readonly string CodeWFBlob = "Showcase.Pages.WindowDemo.CodeWFBlob";
    }


}


namespace Showcase.Windows
{
    public static class WindowDemos
    {
        public static readonly string NativeTitle = "Showcase.Windows.WindowDemos.NativeTitle";
        public static readonly string NativeHeading = "Showcase.Windows.WindowDemos.NativeHeading";
        public static readonly string NativeDescription = "Showcase.Windows.WindowDemos.NativeDescription";
        public static readonly string NativeNoneTitle = "Showcase.Windows.WindowDemos.NativeNoneTitle";
        public static readonly string NativeNoneHeading = "Showcase.Windows.WindowDemos.NativeNoneHeading";
        public static readonly string NativeNoneDescription = "Showcase.Windows.WindowDemos.NativeNoneDescription";
        public static readonly string NativeMoveTitle = "Showcase.Windows.WindowDemos.NativeMoveTitle";
        public static readonly string NativeMoveHeading = "Showcase.Windows.WindowDemos.NativeMoveHeading";
        public static readonly string NativeMoveDescription = "Showcase.Windows.WindowDemos.NativeMoveDescription";
        public static readonly string NativeDarkTitle = "Showcase.Windows.WindowDemos.NativeDarkTitle";
        public static readonly string NativeDarkHeading = "Showcase.Windows.WindowDemos.NativeDarkHeading";
        public static readonly string NativeDarkDescription = "Showcase.Windows.WindowDemos.NativeDarkDescription";
        public static readonly string NativeTallTitle = "Showcase.Windows.WindowDemos.NativeTallTitle";
        public static readonly string NativeTallHeading = "Showcase.Windows.WindowDemos.NativeTallHeading";
        public static readonly string NativeTallDescription = "Showcase.Windows.WindowDemos.NativeTallDescription";
        public static readonly string NativeShapeTitle = "Showcase.Windows.WindowDemos.NativeShapeTitle";
        public static readonly string NativeShapeHeading = "Showcase.Windows.WindowDemos.NativeShapeHeading";
        public static readonly string NativeShapeDescription = "Showcase.Windows.WindowDemos.NativeShapeDescription";
        public static readonly string NativeStarTitle = "Showcase.Windows.WindowDemos.NativeStarTitle";
        public static readonly string NativeStarHeading = "Showcase.Windows.WindowDemos.NativeStarHeading";
        public static readonly string NativeStarDescription = "Showcase.Windows.WindowDemos.NativeStarDescription";
        public static readonly string NativeBlobTitle = "Showcase.Windows.WindowDemos.NativeBlobTitle";
        public static readonly string NativeBlobHeading = "Showcase.Windows.WindowDemos.NativeBlobHeading";
        public static readonly string NativeBlobDescription = "Showcase.Windows.WindowDemos.NativeBlobDescription";
        public static readonly string UrsaDefaultTitle = "Showcase.Windows.WindowDemos.UrsaDefaultTitle";
        public static readonly string UrsaDefaultHeading = "Showcase.Windows.WindowDemos.UrsaDefaultHeading";
        public static readonly string UrsaDefaultDescription = "Showcase.Windows.WindowDemos.UrsaDefaultDescription";
        public static readonly string UrsaNoneTitle = "Showcase.Windows.WindowDemos.UrsaNoneTitle";
        public static readonly string UrsaNoneHeading = "Showcase.Windows.WindowDemos.UrsaNoneHeading";
        public static readonly string UrsaNoneDescription = "Showcase.Windows.WindowDemos.UrsaNoneDescription";
        public static readonly string UrsaMoveTitle = "Showcase.Windows.WindowDemos.UrsaMoveTitle";
        public static readonly string UrsaMoveHeading = "Showcase.Windows.WindowDemos.UrsaMoveHeading";
        public static readonly string UrsaMoveDescription = "Showcase.Windows.WindowDemos.UrsaMoveDescription";
        public static readonly string UrsaDarkTitle = "Showcase.Windows.WindowDemos.UrsaDarkTitle";
        public static readonly string UrsaDarkHeading = "Showcase.Windows.WindowDemos.UrsaDarkHeading";
        public static readonly string UrsaDarkDescription = "Showcase.Windows.WindowDemos.UrsaDarkDescription";
        public static readonly string UrsaAccentTitle = "Showcase.Windows.WindowDemos.UrsaAccentTitle";
        public static readonly string UrsaAccentHeading = "Showcase.Windows.WindowDemos.UrsaAccentHeading";
        public static readonly string UrsaAccentDescription = "Showcase.Windows.WindowDemos.UrsaAccentDescription";
        public static readonly string UrsaCompactTitle = "Showcase.Windows.WindowDemos.UrsaCompactTitle";
        public static readonly string UrsaCompactHeading = "Showcase.Windows.WindowDemos.UrsaCompactHeading";
        public static readonly string UrsaCompactDescription = "Showcase.Windows.WindowDemos.UrsaCompactDescription";
        public static readonly string UrsaTallTitle = "Showcase.Windows.WindowDemos.UrsaTallTitle";
        public static readonly string UrsaTallHeading = "Showcase.Windows.WindowDemos.UrsaTallHeading";
        public static readonly string UrsaTallDescription = "Showcase.Windows.WindowDemos.UrsaTallDescription";
        public static readonly string UrsaShapeTitle = "Showcase.Windows.WindowDemos.UrsaShapeTitle";
        public static readonly string UrsaShapeHeading = "Showcase.Windows.WindowDemos.UrsaShapeHeading";
        public static readonly string UrsaShapeDescription = "Showcase.Windows.WindowDemos.UrsaShapeDescription";
        public static readonly string UrsaStarTitle = "Showcase.Windows.WindowDemos.UrsaStarTitle";
        public static readonly string UrsaStarHeading = "Showcase.Windows.WindowDemos.UrsaStarHeading";
        public static readonly string UrsaStarDescription = "Showcase.Windows.WindowDemos.UrsaStarDescription";
        public static readonly string UrsaBlobTitle = "Showcase.Windows.WindowDemos.UrsaBlobTitle";
        public static readonly string UrsaBlobHeading = "Showcase.Windows.WindowDemos.UrsaBlobHeading";
        public static readonly string UrsaBlobDescription = "Showcase.Windows.WindowDemos.UrsaBlobDescription";
        public static readonly string CodeWFStandardTitle = "Showcase.Windows.WindowDemos.CodeWFStandardTitle";
        public static readonly string CodeWFStandardHeading = "Showcase.Windows.WindowDemos.CodeWFStandardHeading";
        public static readonly string CodeWFStandardDescription = "Showcase.Windows.WindowDemos.CodeWFStandardDescription";
        public static readonly string CodeWFDarkTitle = "Showcase.Windows.WindowDemos.CodeWFDarkTitle";
        public static readonly string CodeWFDarkHeading = "Showcase.Windows.WindowDemos.CodeWFDarkHeading";
        public static readonly string CodeWFDarkDescription = "Showcase.Windows.WindowDemos.CodeWFDarkDescription";
        public static readonly string CodeWFAccentTitle = "Showcase.Windows.WindowDemos.CodeWFAccentTitle";
        public static readonly string CodeWFAccentHeading = "Showcase.Windows.WindowDemos.CodeWFAccentHeading";
        public static readonly string CodeWFAccentDescription = "Showcase.Windows.WindowDemos.CodeWFAccentDescription";
        public static readonly string CodeWFCompactTitle = "Showcase.Windows.WindowDemos.CodeWFCompactTitle";
        public static readonly string CodeWFCompactHeading = "Showcase.Windows.WindowDemos.CodeWFCompactHeading";
        public static readonly string CodeWFCompactDescription = "Showcase.Windows.WindowDemos.CodeWFCompactDescription";
        public static readonly string CodeWFTallTitle = "Showcase.Windows.WindowDemos.CodeWFTallTitle";
        public static readonly string CodeWFTallHeading = "Showcase.Windows.WindowDemos.CodeWFTallHeading";
        public static readonly string CodeWFTallDescription = "Showcase.Windows.WindowDemos.CodeWFTallDescription";
        public static readonly string CodeWFShapeTitle = "Showcase.Windows.WindowDemos.CodeWFShapeTitle";
        public static readonly string CodeWFShapeHeading = "Showcase.Windows.WindowDemos.CodeWFShapeHeading";
        public static readonly string CodeWFShapeDescription = "Showcase.Windows.WindowDemos.CodeWFShapeDescription";
        public static readonly string CodeWFStarTitle = "Showcase.Windows.WindowDemos.CodeWFStarTitle";
        public static readonly string CodeWFStarHeading = "Showcase.Windows.WindowDemos.CodeWFStarHeading";
        public static readonly string CodeWFStarDescription = "Showcase.Windows.WindowDemos.CodeWFStarDescription";
        public static readonly string CodeWFBlobTitle = "Showcase.Windows.WindowDemos.CodeWFBlobTitle";
        public static readonly string CodeWFBlobHeading = "Showcase.Windows.WindowDemos.CodeWFBlobHeading";
        public static readonly string CodeWFBlobDescription = "Showcase.Windows.WindowDemos.CodeWFBlobDescription";
        public static readonly string TitleBarContent = "Showcase.Windows.WindowDemos.TitleBarContent";
        public static readonly string TitleBarContentDesc = "Showcase.Windows.WindowDemos.TitleBarContentDesc";
        public static readonly string InteractiveProperties = "Showcase.Windows.WindowDemos.InteractiveProperties";
        public static readonly string InteractivePropertiesDesc = "Showcase.Windows.WindowDemos.InteractivePropertiesDesc";
        public static readonly string CaptionButtonsGroup = "Showcase.Windows.WindowDemos.CaptionButtonsGroup";
        public static readonly string ShowMinimizeButton = "Showcase.Windows.WindowDemos.ShowMinimizeButton";
        public static readonly string ShowRestoreButton = "Showcase.Windows.WindowDemos.ShowRestoreButton";
        public static readonly string ShowCloseButton = "Showcase.Windows.WindowDemos.ShowCloseButton";
        public static readonly string ShowFullScreenButton = "Showcase.Windows.WindowDemos.ShowFullScreenButton";
        public static readonly string ShowTitleBar = "Showcase.Windows.WindowDemos.ShowTitleBar";
        public static readonly string ShowManagedResizer = "Showcase.Windows.WindowDemos.ShowManagedResizer";
        public static readonly string TitleBarCustomizationGroup = "Showcase.Windows.WindowDemos.TitleBarCustomizationGroup";
        public static readonly string UseCustomLeftContent = "Showcase.Windows.WindowDemos.UseCustomLeftContent";
        public static readonly string ShowTitleBarContent = "Showcase.Windows.WindowDemos.ShowTitleBarContent";
        public static readonly string ShowRightContent = "Showcase.Windows.WindowDemos.ShowRightContent";
        public static readonly string ContentExtendsIntoTitleBar = "Showcase.Windows.WindowDemos.ContentExtendsIntoTitleBar";
        public static readonly string ApplyTitleBarMargin = "Showcase.Windows.WindowDemos.ApplyTitleBarMargin";
        public static readonly string PropertyEffect = "Showcase.Windows.WindowDemos.PropertyEffect";
        public static readonly string PropertyEffectDesc = "Showcase.Windows.WindowDemos.PropertyEffectDesc";
        public static readonly string TitleBarSlotsExperienceDesc = "Showcase.Windows.WindowDemos.TitleBarSlotsExperienceDesc";
        public static readonly string Scenario = "Showcase.Windows.WindowDemos.Scenario";
        public static readonly string ScenarioDesc = "Showcase.Windows.WindowDemos.ScenarioDesc";
        public static readonly string FixedSize = "Showcase.Windows.WindowDemos.FixedSize";
        public static readonly string FixedSizeDesc = "Showcase.Windows.WindowDemos.FixedSizeDesc";
        public static readonly string LightTitleBar = "Showcase.Windows.WindowDemos.LightTitleBar";
        public static readonly string LightTitleBarDesc = "Showcase.Windows.WindowDemos.LightTitleBarDesc";
        public static readonly string CustomProperties = "Showcase.Windows.WindowDemos.CustomProperties";
        public static readonly string WindowBehavior = "Showcase.Windows.WindowDemos.WindowBehavior";
        public static readonly string TitleBarHeight52 = "Showcase.Windows.WindowDemos.TitleBarHeight52";
        public static readonly string TitleBarHeight34 = "Showcase.Windows.WindowDemos.TitleBarHeight34";
        public static readonly string TitleBarHeight44 = "Showcase.Windows.WindowDemos.TitleBarHeight44";
        public static readonly string CanResizeFalse = "Showcase.Windows.WindowDemos.CanResizeFalse";
        public static readonly string TitleBarBrushes = "Showcase.Windows.WindowDemos.TitleBarBrushes";
        public static readonly string TitleBarBackgroundLabel = "Showcase.Windows.WindowDemos.TitleBarBackgroundLabel";
        public static readonly string TitleBarForegroundLabel = "Showcase.Windows.WindowDemos.TitleBarForegroundLabel";
        public static readonly string RightContentLabel = "Showcase.Windows.WindowDemos.RightContentLabel";
        public static readonly string TitleBarSlotsLabel = "Showcase.Windows.WindowDemos.TitleBarSlotsLabel";
        public static readonly string DoubleClickMaximize = "Showcase.Windows.WindowDemos.DoubleClickMaximize";
        public static readonly string ResizeHotZones = "Showcase.Windows.WindowDemos.ResizeHotZones";
        public static readonly string Live = "Showcase.Windows.WindowDemos.Live";
        public static readonly string Online = "Showcase.Windows.WindowDemos.Online";
        public static readonly string Production = "Showcase.Windows.WindowDemos.Production";
        public static readonly string Close = "Showcase.Windows.WindowDemos.Close";
        public static readonly string Cancel = "Showcase.Windows.WindowDemos.Cancel";
    }


}


