









//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CodeWF.Markdown
{

    public static class SampleL
    {

        public static readonly string WindowTitle = "CodeWF.Markdown.SampleL.WindowTitle";

        public static readonly string AppTheme = "CodeWF.Markdown.SampleL.AppTheme";

        public static readonly string TypographyTheme = "CodeWF.Markdown.SampleL.TypographyTheme";

        public static readonly string Language = "CodeWF.Markdown.SampleL.Language";

        public static readonly string MarkdownInput = "CodeWF.Markdown.SampleL.MarkdownInput";

        public static readonly string StartIncrementalDemo = "CodeWF.Markdown.SampleL.StartIncrementalDemo";

        public static readonly string StopIncrementalDemo = "CodeWF.Markdown.SampleL.StopIncrementalDemo";

    }


}

